### ISSUE TITLE
use safe auth when supported 

### ISSUE THREAD

**Issue by lnguyen** [blacksmith-community/blacksmith-boshrelease#2]

**Comment by lnguyen** [comment]
https://github.com/jhunt/safe/issues/21

**Comment by jhunt** [comment]
Check out safe v0.0.16 (https://github.com/jhunt/safe/releases/tag/v0.0.16)

**Comment by jhunt** [comment]
Blacksmith now manages its own vault in-code, so there is no reliance on `safe` anymore.
